language: android
jdk: oraclejdk7

android:
  components:
    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-16

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-16

before_install:
  - chmod +x gradlew
  - chmod -R +rw

notifications:
  email: false